### ISSUE TITLE
Add option for being notified when Marks of Grace are about to despawn

### ISSUE THREAD

**Issue by QuestingPet** [Cyborger1/marks-of-grace-counter#2]
According to [the wiki](https://oldschool.runescape.wiki/w/Mark_of_grace) Marks of Grace despawn after 10 minutes. New marks of grace that stack on previous ones will reset the timer, useful for Ardy course.

While half-paying attention and sometimes AFKing, it would be nice if we could be notified if our stack of marks are about to despawn, so that we don't lose them. Perhaps a config that specifies the number of minutes to be notified since last spawn, and negative would disable it? Whatever you think works best. 

Personally, I'd like to know if I only have a minute or two remaining until they despawn, so that I can make sure I don't AFK too long and can retrieve them. Especially if I'm watching a video or doing something else on my monitor and forget about it.

Let me know what you think. Thanks!

**Comment by Cyborger1** [comment]
I put up a pull request on the plugin hub to add this feature, please let me know if everything's good when it's accepted and you get the update on your side.

**Comment by Cyborger1** [comment]
Update is through, please let me know if it's good.

**Comment by QuestingPet** [comment]
Works perfectly! At first I was confused because it didn't work, but then I realized the setting is disabled by default (I just didn't bother looking). Seems to work great now, thanks! And thanks for the swift implementation!

**Comment by QuestingPet** [comment]
So everything works great, though one additional suggestion. It would be nice if the message "Your Marks of Grace are about to despawn!" included the number of marks, like "Your 32 Marks of Grace ..."

There are times (yes already) where I afk too long even after seeing the message (totally my fault), and it would have been nice to know how many marks I lost haha. Could probably just use the same number as whatever "Marks on Ground" is populated from.

**Comment by Cyborger1** [comment]
I already have a plugin hub request for a refactor of this plugin that I'd like to have go through first, but once that's done I'll put a new request for a change that adds `(x Marks)` at the end of the notification message. I already wrote the change so it shouldn't be too long once the first request is through.

While it doesn't apply in your case, one of the changes from the refactor is being able to notify independently for separate stacks of marks on courses that aren't the Ardougne course, since I'm now keeping track of the last spawn time for each stack.

You should expect to see messages in this format once both changes are through:
`Your Marks of Grace stack is about to despawn! (5 Marks)`
`One of your Marks of Grace stacks is about to despawn! (1 Mark)`

**Comment by Cyborger1** [comment]
Please take another look now

**Comment by Cyborger1** [comment]
I'm closing this issue as the plugin has been updated with the requested change 2 days ago. Please reopen if you need anything else.

**Comment by QuestingPet** [comment]
Just tested this and works for me! Thank you!
